### ISSUE TITLE
command issue

### ISSUE THREAD

**Issue by cintuzu** [ahmeterdem1/SSL-Messager#1]
when in chat, sometimes commands like :online: , :toggle: does not work. changing username solves the issue (i think only for that moment),

**Comment by ahmeterdem1** [comment]
The reason is identified as a left out else case code in the intro_handler function which handles first log in/sign up interactions in the server. This left out code resulted in people being able to log in as everything no matter the database. These users only existed in the ram therefore they were temporary and unreachable by others including the server itself. This resulted in server responses not making it to the temporary user created. Commands didn't get any responses, they didn't work. However these users were completely visible by every other user. These users messages made it through just fine. Now, this bug is fixed. Some other bugs were arising from the same issue, they are also fixed now.
